### ISSUE TITLE
Maybe allow some warnings

### ISSUE THREAD

**Issue by MovingtoMars** [yberreby/rgo#15]
There are a couple of pesky warnings that keep coming up, but are pretty harmless. How about `#[allow(dead_code)]`?

**Comment by yberreby** [comment]
I'm not sure this would be a good thing, because we will very likely forget to remove it when we should, and dead code is something we _really_ want to avoid in the long run. These warnings (I count three) should also disappear pretty quickly, once the parser is complete.

**Comment by yberreby** [comment]
A bit off-topic: I won't be able to comment on issues / PRs, except on Sundays - and even then it will be hard. I have a lot of work to do for my studies, and I can't afford being distracted until it is done. I love working on `rgo` and discussing design decisions, but I'm kind of pressed for time right now.

**Comment by MovingtoMars** [comment]
No problem, man.

**Comment by yberreby** [comment]
Glad you understand! You're free to merge PRs in the meantime, since you have push access. Please just try to:
- keep the git history clean
- run `rustfmt`
- leave `XXX`-style comments in any place we'd want to revisit in the future

See [CONTRIBUTING.md](https://github.com/yberreby/rgo/blob/master/CONTRIBUTING.md) for details.

See you later, and thanks for your PRs. This is really nice of you.

**Comment by MovingtoMars** [comment]
Thanks :)
(I just installed a rustfmt plugin)
