### ISSUE TITLE
Token spans

### ISSUE THREAD

**Issue by MovingtoMars** [yberreby/rgo#9]
Right now, tokens only store the beginning offsets. For nice error messages, spans (start and end offsets) are needed,

**Comment by yberreby** [comment]
My initial idea was to use the start offset of the next token as the end of the current one, but I realize this approach ignores whitespace, so 👍 .

Memory usage will have to watched, though, since all tokens are being added to a vector to improve cache usage. If it becomes problematic, we might want to store only up to `N` tokens, parse that, then rinse and repeat, in order to avoid eating up too much memory when tokenizing large source files.

Go's parser uses a different approach altogether: parsing and lexing are performed at the same time. Tokens are consumed immediately after being produced.

**Comment by MovingtoMars** [comment]
Closed by #10
